import {
  BookIcon,
  ComposeIcon,
  EnvelopeIcon,
  HomeIcon,
  ImageIcon,
  LinkIcon,
  PlayIcon,
  ProjectsIcon,
  RocketIcon,
  StarIcon,
  UserIcon,
} from '@sanity/icons'
import {defineArrayMember, defineField, defineType} from 'sanity'
import {validateRequiredLocales} from '../validation/localization'

export const portfolioPage = defineType({
  name: 'portfolioPage',
  title: 'Portfolio page',
  type: 'document',
  icon: HomeIcon,
  groups: [
    {name: 'profile', title: '01 · Profile', icon: UserIcon, default: true},
    {name: 'resume', title: '02 · Resume', icon: BookIcon},
    {name: 'theatre', title: '03 · Theatre', icon: PlayIcon},
    {name: 'film', title: '04 · Film & TV', icon: ProjectsIcon},
    {name: 'awards', title: '05 · Awards', icon: StarIcon},
    {name: 'teaching', title: '06 · Teaching', icon: ComposeIcon},
    {name: 'upcoming', title: '07 · Upcoming', icon: RocketIcon},
    {name: 'gallery', title: '08 · Gallery', icon: ImageIcon},
    {name: 'downloads', title: '09 · Downloads', icon: LinkIcon},
    {name: 'contact', title: '10 · Contact', icon: EnvelopeIcon},
    {name: 'seo', title: 'SEO', icon: ProjectsIcon},
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'localizedString',
      group: 'profile',
      validation: (rule) => rule.required().custom(validateRequiredLocales),
    }),
    defineField({
      name: 'intro',
      title: 'Introduction',
      type: 'localizedBlockContent',
      group: 'profile',
      validation: (rule) => rule.required().warning('Add the opening profile text.'),
    }),
    defineField({
      name: 'headshot',
      title: 'Profile portrait',
      description: 'Used in the opening section. Set the hotspot on the face.',
      type: 'portfolioImage',
      group: 'profile',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'roles',
      title: 'Roles',
      type: 'array',
      group: 'profile',
      of: [defineArrayMember({type: 'profileRole'})],
      validation: (rule) => rule.min(1).required(),
    }),
    defineField({
      name: 'resumeHeading',
      title: 'Resume heading',
      type: 'localizedString',
      group: 'resume',
    }),
    defineField({
      name: 'resumeBody',
      title: 'Resume body',
      type: 'localizedBlockContent',
      group: 'resume',
    }),
    defineField({
      name: 'resumeImage',
      title: 'Resume image',
      type: 'portfolioImage',
      group: 'resume',
    }),
    defineField({
      name: 'education',
      title: 'Education',
      type: 'array',
      group: 'resume',
      of: [defineArrayMember({type: 'educationItem'})],
    }),
    defineField({
      name: 'skills',
      title: 'Skills',
      type: 'array',
      group: 'resume',
      of: [defineArrayMember({type: 'skillItem'})],
    }),
    defineField({
      name: 'sectionIntroductions',
      title: 'Section headings and introductions',
      type: 'array',
      group: ['theatre', 'film', 'awards', 'teaching', 'upcoming', 'gallery', 'downloads'],
      of: [defineArrayMember({type: 'sectionIntroduction'})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'productions',
      title: 'Production order on the website',
      description: 'Drag to change the order. Edit production details from the Productions menu.',
      type: 'array',
      group: ['theatre', 'film'],
      of: [defineArrayMember({type: 'reference', to: [{type: 'production'}]})],
      validation: (rule) => rule.unique().min(1).required(),
    }),
    defineField({
      name: 'awards',
      title: 'Awards',
      type: 'array',
      group: 'awards',
      of: [defineArrayMember({type: 'awardItem'})],
    }),
    defineField({
      name: 'teachingExperiences',
      title: 'Teaching experiences',
      type: 'array',
      group: 'teaching',
      of: [defineArrayMember({type: 'teachingExperience'})],
    }),
    defineField({
      name: 'upcomingWork',
      title: 'Upcoming work',
      type: 'upcomingWork',
      group: 'upcoming',
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'gallery',
      of: [defineArrayMember({type: 'galleryImage'})],
    }),
    defineField({
      name: 'customSections',
      title: 'Custom sections',
      type: 'array',
      group: ['theatre', 'film', 'awards', 'teaching', 'upcoming', 'gallery'],
      of: [defineArrayMember({type: 'customSection'})],
    }),
    defineField({name: 'contact', title: 'Contact', type: 'contactInformation', group: 'contact'}),
    defineField({name: 'downloads', title: 'Downloads', type: 'downloadLinks', group: 'downloads'}),
    defineField({name: 'seo', title: 'Search & social sharing', type: 'seoMetadata', group: 'seo'}),
    defineField({
      name: 'footerText',
      title: 'Footer text',
      type: 'localizedString',
      group: 'contact',
    }),
    defineField({
      name: 'migration',
      title: 'Migration metadata',
      type: 'migrationMetadata',
      readOnly: true,
      hidden: true,
    }),
  ],
  preview: {
    select: {media: 'headshot'},
    prepare({media}) {
      return {title: 'Portfolio page', subtitle: 'English + فارسی', media}
    },
  },
})
