import {buildLegacyTheme} from 'sanity'

export const monaStudioTheme = buildLegacyTheme({
  '--font-family-base': 'Google Sans, Inter, Roboto, Estedad, system-ui, sans-serif',
  '--font-family-monospace': 'JetBrains Mono, ui-monospace, monospace',
  '--black': '#1d1b20',
  '--white': '#fffbff',
  '--brand-primary': '#6750a4',
  '--component-bg': '#fffbff',
  '--component-text-color': '#1d1b20',
  '--default-button-color': '#49454f',
  '--default-button-primary-color': '#6750a4',
  '--default-button-success-color': '#006c48',
  '--default-button-warning-color': '#8b5000',
  '--default-button-danger-color': '#ba1a1a',
  '--focus-color': '#7d5260',
  '--gray-base': '#79747e',
  '--gray': '#79747e',
  '--main-navigation-color': '#f7f2fa',
  '--main-navigation-color--inverted': '#1d1b20',
  '--state-info-color': '#006a6a',
  '--state-success-color': '#006c48',
  '--state-warning-color': '#8b5000',
  '--state-danger-color': '#ba1a1a',
})
